import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,Bot,FileText,ShieldCheck,Stethoscope,Upload} from 'lucide-react';
import './styles.css';
const API=import.meta.env.VITE_API_URL || 'http://localhost:8000';
function App(){
 const [token,setToken]=useState(''); const [patients,setPatients]=useState([]); const [mrn,setMrn]=useState('MRN-1023'); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [question,setQuestion]=useState('What are the main findings in the uploaded document?'); const [file,setFile]=useState(null); const [documents,setDocuments]=useState([]); const [uploading,setUploading]=useState(false); const [notice,setNotice]=useState('');
 async function login(){const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'doctor@medintel.demo',password:'doctor123'})});const d=await r.json();setToken(d.access_token)}
 useEffect(()=>{login()},[]);
 useEffect(()=>{if(token)fetch(API+'/patients',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json()).then(setPatients)},[token]);
 useEffect(()=>{if(token)refreshDocuments()},[token,mrn]);
 async function refreshDocuments(){const r=await fetch(`${API}/patients/${mrn}/documents`,{headers:{Authorization:'Bearer '+token}});if(r.ok)setDocuments(await r.json())}
 async function uploadPdf(){if(!file)return setNotice('Choose a PDF first.');setUploading(true);setNotice('');setResult(null);const form=new FormData();form.append('file',file);const r=await fetch(`${API}/patients/${mrn}/documents`,{method:'POST',headers:{Authorization:'Bearer '+token},body:form});const d=await r.json();if(!r.ok)setNotice(d.detail||'Upload failed.');else{setNotice(`Uploaded ${d.filename} - ${d.text_pages} readable pages - ${d.chunks} chunks`);setFile(null);await refreshDocuments()}setUploading(false)}
 async function ask(){if(!question.trim())return;setLoading(true);const r=await fetch(API+'/agent',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({mrn,message:question})});setResult(await r.json());setLoading(false)}
 const patient=patients.find(p=>p.mrn===mrn);
 return <div className="shell"><aside><div className="brand"><Stethoscope/> MedIntel</div><p>Workflow AI Demo</p><nav><span><Activity/> Patient workspace</span><span><FileText/> PDF RAG</span><span><Bot/> Agent activity</span><span><ShieldCheck/> Privacy controls</span></nav></aside><main><header><div><h1>Workflow Agent</h1><p>Synthetic demo - PDF RAG + agent workflow</p></div><span className="badge">Protected demo</span></header><section className="grid"><div className="card"><h3>Patient Context</h3><select value={mrn} onChange={e=>{setMrn(e.target.value);setResult(null)}}>{patients.map(p=><option key={p.mrn}>{p.mrn}</option>)}</select><div className="patient">{patient?.name||'Loading patient...'}<small>{patient?.age} yrs - {patient?.sex}</small></div></div><div className="card"><h3><Upload size={18}/> Upload PDF</h3><p className="muted">Text-based PDFs up to 10 MB, scoped to the selected MRN.</p><input className="file" type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><button onClick={uploadPdf} disabled={!token||uploading}>{uploading?'Reading PDF...':'Upload & index PDF'}</button>{notice&&<p className="notice">{notice}</p>}</div></section><section className="card"><div className="section-head"><h3>Uploaded Documents</h3><span>{documents.length} file(s)</span></div>{documents.length?documents.map(d=><div className="doc" key={d.document_id}><FileText size={18}/><div><strong>{d.filename}</strong><small>{d.text_pages} readable pages - {d.chunks} chunks</small></div></div>):<p className="muted">No PDF uploaded yet. The agent will use the built-in synthetic reports until you upload one.</p>}</section><section className="card"><h3>Ask the Agent</h3><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a question about the uploaded PDF..."/><button onClick={ask} disabled={!token||loading}>{loading?'Agent retrieving evidence...':'Ask MedIntel'}</button></section>{result&&<><section className="grid"><div className="card"><h3>Agent Activity</h3><div className="tools">{result.tools_used.map(t=><span key={t}>{t}</span>)}</div></div><div className="card"><h3>Sources</h3>{result.sources?.length?result.sources.map((s,i)=><div className="source" key={i}><strong>{s.filename}</strong><span>Page {s.page}</span></div>):<p className="muted">No uploaded-PDF source used.</p>}</div></section><section className="card"><h3>Grounded Answer</h3><p>{result.answer}</p></section><section className="card"><h3>Plain-Language Explanation</h3><p>{result.patient_explanation}</p><div className="warning">{result.disclaimer}</div></section></>}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
